services:
  dev_mysql:
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - /Users/smallj/Desktop/docker/dev/mysql_docker/data2:/var/lib/mysql:rw
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: preonboarding
      MYSQL_DATABASE: wanted
